favicon_getter/urls.py
from django.conf.urls import url
from codefisher_apps.favicon_getter import views

urlpatterns = [
    url(r'^$', views.index, name='ico-index'),
    url(r'^get_icons/', views.favicons, name='ico-get-favicons'),
    url(r'^favicon/', views.favicon, name='ico-favicons'),
]

favicon_getter/views.py
try:
    import urlparse
    from HTMLParser import HTMLParser
except ImportError:
    import urllib.parse as urlparse
    from html.parser import HTMLParser
import io
import operator
import subprocess
import base64
import requests

from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django import forms
from django.core.files.uploadhandler import TemporaryFileUploadHandler
from django.http import HttpResponse

from PIL import Image

class FavIconParser(HTMLParser):

    def __init__(self, url):
        HTMLParser.__init__(self)
        self._icons = []
        self._url = url

    def handle_starttag(self, tag, attrs):
        if tag == "link":
            attrs = dict(attrs)
            if attrs["rel"].find("icon") != -1 and "href" in attrs:
                self._icons.append(urlparse.urljoin(self._url, attrs["href"]))

    def get_icon(self):
        if not self._icons:
            return None
        return self._icons.pop(0)

def get_favicon_url(url):
    try:
        data = requests.get(url).text
    except IOError:
        return None
    try:
        parser = FavIconParser(url)
        parser.feed(data)
        parser.close()
    except:
        return None
    icon_url = parser.get_icon()
    if not icon_url:
        icon_url = urlparse.urljoin(url, "/favicon.ico")
    return icon_url

def file_to_images(fp):
    try:
        image = Image.open(fp)
        if "sizes" in image.info:
            images = []
            for size in image.info["sizes"]:
                image.size = size
                im = Image.new("RGBA", size)
                im.putdata(image.getdata())
                images.append((im, im.size))
            return images
        return [(image, image.size)]
    except:
        return None

def get_favicon_as_images(url=None, favicon_url=None):
    try:
        if not favicon_url:
            favicon_url = get_favicon_url(url)
        fav = requests.get(favicon_url, timeout=10)
        icon_fp = io.BytesIO(fav.content)
        fav.close()
        icons = file_to_images(icon_fp)
        #icon_fp.close() # we get errors latter if we close this now
        return icons
    except:
        return None
    
@csrf_exempt
def favicons(request):
    if not request.POST.get("url"):
        return HttpResponse("fail")
    url = request.POST.get("url")
    parsed_url = urlparse.urlparse(url)
    if parsed_url[0] == "":
        url = "http://" + url
    elif parsed_url[0] not in ["http", "https", "ftp", "ftps"]:
        return HttpResponse("fail")
    icons = get_favicon_as_images(url)  
    if icons is None:
        return HttpResponse("fail")
    icons = get_favicon_as_images(url)  
    tags = get_tags(icons)
    return HttpResponse("\n".join(tags))

def get_sized_icons(url, sizes):
    icons = get_favicon_as_images(url)
    if icons is None:
        return None
    largest, _ = max(icons, key=operator.itemgetter(1))
    result = {}
    for image, size in icons:
        width, height = size[0:2]
        if width == height and height in sizes:
            result[width] = image
    for size in set(sizes).difference(set(result.keys())):
        result[size] = largest.resize((size, size))
    return result

@csrf_exempt # we do this, or we can't change the upload_handlers
def index(request):
    request.upload_handlers.insert(0, TemporaryFileUploadHandler())
    tags = []
    ico = True
    if request.method == "POST":
        if "ico-to-png" in request.POST:
            if "ico-file" in request.FILES:
                icons = file_to_images(request.FILES["ico-file"].file)
                if icons:
                    tags = get_tags(icons)
        elif "png-to-ico" in request.POST:
            name = "png-file-1"
            index = 1
            files = []
            while name in request.FILES:
                files.append(request.FILES[name].temporary_file_path())
                index += 1
                name = "png-file-%s" % index
            try:
                ico_data = subprocess.check_output(["icotool", "-c"] + files)
                responce = HttpResponse(ico_data, content_type="application/octet-stream")
                responce['Content-Disposition'] = 'attachment; filename=icon.ico'
                return responce
            except subprocess.CalledProcessError:
                ico = False
    data = {
        "title": "ICO tools",
          "pngs": "\n".join(tags),
          "ico": ico,
    }
    return render(request, "ico/index.html", data)

class  UrlForm(forms.Form):
    url = forms.URLField(label="Website Url")
    
def get_tags(icons):
    tags = []
    for icon, size in icons:
        value = io.BytesIO()
        icon.save(value, "png")
        data = "data:image/png;base64," + base64.b64encode(value.getvalue())
        value.close()
        tags.append('<img style="margin:10px;" src="%s" width="%s" height="%s" alt="">' % (data, size, size))
    return tags
    
def favicon(request):
    tags = []
    submitted = False
    favicon_url = None
    if request.method == "POST":
        form = UrlForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            favicon_url = get_favicon_url(url)
            icons = get_favicon_as_images(favicon_url=favicon_url)
            if icons:
                tags = get_tags(icons)
                submitted = True
    else:
        form = UrlForm()
    data = {
            "title": "Get Favicon",
            "form": form,
            "tags": "".join(tags),
            "submitted": submitted,
            "favicon_url": favicon_url,
    }
    return render(request, "ico/favicon.html", data)

favicon_getter/templates/ico/favicon.html
{% extends "base.html" %}

{% block content %}

<p>
	In the form below simply type a web site name, and if possible the images from its favicon will be extracted and displayed, along with the actual icon.
</p>
	
	<form action="{% url 'ico-favicons' %}" id="favicon-form" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p><input type="submit" value="Submit" /></p>
    </form>
    <div id="favicons">
    	{% if submitted %}
    		{% if tags %} <div>Images:<br /> {{ tags|safe }}</div> {% else %} <p>There are no favicons for this site.</p> {% endif %}
    		{% if favicon_url %}<div>Favicon:<br /> <img style="margin:10px;" src="{{ favicon_url }}" alt=""></div>{% endif %}
    	{% endif %}
    </div>
    
	<script type="text/javascript">
	function loadFavIcons() {
			$('#favicons').html("Loading...");
			$.ajax({
				url: '/ico/get_icons/',
				type: "POST",
				data: $('#favicon-form').serialize(),
				dataType: "html",
				success: function(msg){
					if(msg == "fail") {
						$('#favicons').html("There are no favicons for this site.");
					} else {
						$('#favicons').html(msg);
					}
				},
				error: function(jqXHR, textStatus, errorThrown){
					$('#favicons').html("There are no favicons for this site.");
				}
			});
			return true;
		}
		$('#id_url').on("change", loadFavIcons);
	</script>
{% endblock %}

favicon_getter/templates/ico/index.html
{% extends "base.html" %}

{% block content %}
{% comment %}
<h2>File to Icon</h2>

<p>
 The below form allows you to get an icon out of a most files that can contain them.  For example the firefox.exe that is used to run Firefox.  The icon can then be saved as an .ICO file.  This has only been tested to work in Firefox on Windows.  I don't know what will happen on other operating systems, and I know it will not work in other browsers.  JavaScript is required.
</p>

<script type="text/javascript"><!--
 function getIcon(form){ 
  var iconPath = 'moz-icon:file:///'+form.file.value+'?size='+parseInt(form.size.value);
  var icon = document.getElementById('icon');
  icon.src = iconPath;
  icon.setAttribute('width', icon.naturalWidth);
  icon.setAttribute('height', icon.naturalHeight);
  form.size.value = icon.naturalWidth;
 }
//-->
</script>

<form action="#icon" onsumbit="return false" method="post">
 <div>
 <p>
  Select a file that you would like to use.
 </p>
 <input type="file" name="file">
 <p>
  Pick a size for the icon you want.  The closest match will be used.
 </p>
 <input type="text" name="size" value="32" size="3">
 <input type="button" value="Get Icon" onclick="getIcon(this.form);">
 </div>
</form>

<img src="/images/dot.gif" id="icon" alt="" width="0" height="0">
{% endcomment %}

<h2>From ICO to PNG</h2>

<p>
 The above form produces .ICO files.  This is fine, expect many image programs can't handle .ICO files.  So here we convert them to PNGs that can be opened by almost all image editors.
</p>

<form action="{% url 'ico-index' %}#png-files" enctype="multipart/form-data" method="post">
 <div>
 <p>
  Put in the file that you would like to use.  If this is the image used above, you will need to save it to your computer first then put it in the box below.
 </p>
 <input type="file" name="ico-file">
 <input type="submit" name="ico-to-png" value="Get PNG">
 </div>
</form>
<div style="text-align:center" id="png-files">
	{{ pngs|safe }}
</div>

<h2>PNG to ICO</h2>

<p>
 You can also the the reverse of the above and pack multiple PNGs into one ICO file.  Only the use of PNGs at this stage is supported.  The maximum icon size is 256 which is imposed by the ICO file format itself, anything larger could result in a corrupt icon.
</p>

<form action="{% url 'ico-index' %}#ico-file" enctype="multipart/form-data" method="post">
 <div>
 <p>
  Put in the file that you would like to use.  If this is the image used above, you will need to save it to your computer first then put it in the box below.
 </p>
 <div id="inputs">
  <input type="file" id="png-file-1" style="display:block" name="png-file-1">
 </div>
 <input type="button" value="Add Another PNG" onclick="addNewFile(this.form)">
 <div><input type="submit" name="png-to-ico" value="Get Ico"></div>
 </div>
</form>
<script type="text/javascript"><!--
 function addNewFile(form){
  var box = document.getElementById('inputs');
  var div = document.createElement('div');
  var input = document.createElement('input');
  var i = 1;
  while(document.getElementById('png-file-'+i)){
   i++;
  }
  input.id = 'png-file-' +i;
  input.name = 'png-file-' +i;
  input.type = 'file';
  div.appendChild(input);
  var minus = document.createElement('input');
  minus.type = 'button';
  minus.value = 'Remove'
  minus.setAttribute('onclick','removeFile(this);');
  div.appendChild(minus);
  box.appendChild(div);
 }
 function removeFile(item){
  item.parentNode.parentNode.removeChild(item.parentNode);
 }
//--></script>

<div style="text-align:center" id="ico-file">
	{% if ico == False %} <p>Failed to Create File.</p> {% endif %}
</div>

{% endblock %}